'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2goclient 8 "17 May 2011" "Version 3.0.1.x" "X2go Client (Qt4)"
.SH NAME
x2goclient \- Client application to launch server-side X2go sessions.
.SH SYNOPSIS
'nh
.fi
.ad l
\fBx2goclient\fR  <options>

.SH DESCRIPTION
\fBx2goclient\fR is a GUI application for launching server-side X2go sessions.
.PP
.SH OPTIONS
\fBx2goclient\fR has the following options: ... (TODO)
.PP
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2go project
(http://www.x2go.org).
