#############################################################################
# Makefile for building: x2goclient
# Generated by qmake (3.1) (Qt 5.9.1)
# Project:  x2goclient.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile x2goclient.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DCFGCLIENT -D__linux__ -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = x2goclient4.1.2.0
DISTDIR = /home/kuscsik/code/x2go/x2goclient/.tmp/x2goclient4.1.2.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lssh -lssh_threads -lldap -lcups -lX11 -lXpm -lQt5Svg -lQt5Widgets -lQt5X11Extras -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/sharewidget.cpp \
		src/settingswidget.cpp \
		src/mediawidget.cpp \
		src/configwidget.cpp \
		src/sessionwidget.cpp \
		src/connectionwidget.cpp \
		src/configdialog.cpp \
		src/editconnectiondialog.cpp \
		src/exportdialog.cpp \
		src/imgframe.cpp \
		src/LDAPSession.cpp \
		src/onmainwindow.cpp \
		src/sessionbutton.cpp \
		src/sessionmanagedialog.cpp \
		src/sshmasterconnection.cpp \
		src/sshprocess.cpp \
		src/SVGFrame.cpp \
		src/InteractionDialog.cpp \
		src/userbutton.cpp \
		src/x2gologdebug.cpp \
		src/printprocess.cpp \
		src/cupsprint.cpp \
		src/cupsprintwidget.cpp \
		src/cupsprintersettingsdialog.cpp \
		src/printwidget.cpp \
		src/printercmddialog.cpp \
		src/printdialog.cpp \
		src/wapi.cpp \
		src/clicklineedit.cpp \
		src/httpbrokerclient.cpp \
		src/ongetpass.cpp \
		src/x2gosettings.cpp \
		src/brokerpassdlg.cpp \
		src/contest.cpp \
		src/xsettingswidget.cpp \
		src/appdialog.cpp \
		src/x2goutils.cpp \
		src/helpdialog.cpp \
		src/sessionexplorer.cpp \
		src/folderbutton.cpp \
		src/folderexplorer.cpp \
		src/non_modal_messagebox.cpp \
		src/help.cpp \
		src/unixhelper.cpp \
		src/compat.cpp \
		src/pulsemanager.cpp \
		src/x2goclient.cpp qrc_resources.cpp \
		moc_configdialog.cpp \
		moc_editconnectiondialog.cpp \
		moc_exportdialog.cpp \
		moc_imgframe.cpp \
		moc_onmainwindow.cpp \
		moc_sessionbutton.cpp \
		moc_sessionmanagedialog.cpp \
		moc_sshmasterconnection.cpp \
		moc_sshprocess.cpp \
		moc_SVGFrame.cpp \
		moc_InteractionDialog.cpp \
		moc_userbutton.cpp \
		moc_printprocess.cpp \
		moc_cupsprintwidget.cpp \
		moc_cupsprintersettingsdialog.cpp \
		moc_printwidget.cpp \
		moc_printercmddialog.cpp \
		moc_printdialog.cpp \
		moc_sessionwidget.cpp \
		moc_connectionwidget.cpp \
		moc_settingswidget.cpp \
		moc_mediawidget.cpp \
		moc_sharewidget.cpp \
		moc_clicklineedit.cpp \
		moc_httpbrokerclient.cpp \
		moc_brokerpassdlg.cpp \
		moc_contest.cpp \
		moc_xsettingswidget.cpp \
		moc_appdialog.cpp \
		moc_sessionexplorer.cpp \
		moc_folderbutton.cpp \
		moc_folderexplorer.cpp \
		moc_pulsemanager.cpp
OBJECTS       = sharewidget.o \
		settingswidget.o \
		mediawidget.o \
		configwidget.o \
		sessionwidget.o \
		connectionwidget.o \
		configdialog.o \
		editconnectiondialog.o \
		exportdialog.o \
		imgframe.o \
		LDAPSession.o \
		onmainwindow.o \
		sessionbutton.o \
		sessionmanagedialog.o \
		sshmasterconnection.o \
		sshprocess.o \
		SVGFrame.o \
		InteractionDialog.o \
		userbutton.o \
		x2gologdebug.o \
		printprocess.o \
		cupsprint.o \
		cupsprintwidget.o \
		cupsprintersettingsdialog.o \
		printwidget.o \
		printercmddialog.o \
		printdialog.o \
		wapi.o \
		clicklineedit.o \
		httpbrokerclient.o \
		ongetpass.o \
		x2gosettings.o \
		brokerpassdlg.o \
		contest.o \
		xsettingswidget.o \
		appdialog.o \
		x2goutils.o \
		helpdialog.o \
		sessionexplorer.o \
		folderbutton.o \
		folderexplorer.o \
		non_modal_messagebox.o \
		help.o \
		unixhelper.o \
		compat.o \
		pulsemanager.o \
		x2goclient.o \
		qrc_resources.o \
		moc_configdialog.o \
		moc_editconnectiondialog.o \
		moc_exportdialog.o \
		moc_imgframe.o \
		moc_onmainwindow.o \
		moc_sessionbutton.o \
		moc_sessionmanagedialog.o \
		moc_sshmasterconnection.o \
		moc_sshprocess.o \
		moc_SVGFrame.o \
		moc_InteractionDialog.o \
		moc_userbutton.o \
		moc_printprocess.o \
		moc_cupsprintwidget.o \
		moc_cupsprintersettingsdialog.o \
		moc_printwidget.o \
		moc_printercmddialog.o \
		moc_printdialog.o \
		moc_sessionwidget.o \
		moc_connectionwidget.o \
		moc_settingswidget.o \
		moc_mediawidget.o \
		moc_sharewidget.o \
		moc_clicklineedit.o \
		moc_httpbrokerclient.o \
		moc_brokerpassdlg.o \
		moc_contest.o \
		moc_xsettingswidget.o \
		moc_appdialog.o \
		moc_sessionexplorer.o \
		moc_folderbutton.o \
		moc_folderexplorer.o \
		moc_pulsemanager.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		x2goclientconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		x2goclient.pro src/configdialog.h \
		src/editconnectiondialog.h \
		src/exportdialog.h \
		src/imgframe.h \
		src/LDAPSession.h \
		src/onmainwindow.h \
		src/sessionbutton.h \
		src/sessionmanagedialog.h \
		src/sshmasterconnection.h \
		src/sshprocess.h \
		src/SVGFrame.h \
		src/InteractionDialog.h \
		src/userbutton.h \
		src/x2goclientconfig.h \
		src/x2gologdebug.h \
		src/printprocess.h \
		src/cupsprint.h \
		src/cupsprintwidget.h \
		src/cupsprintersettingsdialog.h \
		src/printwidget.h \
		src/printercmddialog.h \
		src/printdialog.h \
		src/wapi.h \
		src/sessionwidget.h \
		src/configwidget.h \
		src/connectionwidget.h \
		src/settingswidget.h \
		src/mediawidget.h \
		src/sharewidget.h \
		src/clicklineedit.h \
		src/httpbrokerclient.h \
		src/ongetpass.h \
		src/onmainwindow_privat.h \
		src/x2gosettings.h \
		src/brokerpassdlg.h \
		src/contest.h \
		src/xsettingswidget.h \
		src/appdialog.h \
		src/x2goutils.h \
		src/helpdialog.h \
		src/sessionexplorer.h \
		src/folderbutton.h \
		src/folderexplorer.h \
		src/non_modal_messagebox.h \
		src/help.h \
		src/unixhelper.h \
		src/compat.h \
		src/pulsemanager.h src/sharewidget.cpp \
		src/settingswidget.cpp \
		src/mediawidget.cpp \
		src/configwidget.cpp \
		src/sessionwidget.cpp \
		src/connectionwidget.cpp \
		src/configdialog.cpp \
		src/editconnectiondialog.cpp \
		src/exportdialog.cpp \
		src/imgframe.cpp \
		src/LDAPSession.cpp \
		src/onmainwindow.cpp \
		src/sessionbutton.cpp \
		src/sessionmanagedialog.cpp \
		src/sshmasterconnection.cpp \
		src/sshprocess.cpp \
		src/SVGFrame.cpp \
		src/InteractionDialog.cpp \
		src/userbutton.cpp \
		src/x2gologdebug.cpp \
		src/printprocess.cpp \
		src/cupsprint.cpp \
		src/cupsprintwidget.cpp \
		src/cupsprintersettingsdialog.cpp \
		src/printwidget.cpp \
		src/printercmddialog.cpp \
		src/printdialog.cpp \
		src/wapi.cpp \
		src/clicklineedit.cpp \
		src/httpbrokerclient.cpp \
		src/ongetpass.cpp \
		src/x2gosettings.cpp \
		src/brokerpassdlg.cpp \
		src/contest.cpp \
		src/xsettingswidget.cpp \
		src/appdialog.cpp \
		src/x2goutils.cpp \
		src/helpdialog.cpp \
		src/sessionexplorer.cpp \
		src/folderbutton.cpp \
		src/folderexplorer.cpp \
		src/non_modal_messagebox.cpp \
		src/help.cpp \
		src/unixhelper.cpp \
		src/compat.cpp \
		src/pulsemanager.cpp \
		src/x2goclient.cpp
QMAKE_TARGET  = x2goclient
DESTDIR       = 
TARGET        = x2goclient


first: all
####### Build rules

$(TARGET): compiler_TSQM_make_all ui_cupsprintsettingsdialog.h ui_cupsprintwidget.h ui_printdialog.h ui_printercmddialog.h ui_printwidget.h ui_xsettingsui.h ui_brokerpassdialog.h ui_contest.h ui_appdialog.h ui_helpdialog.h ui_folderexplorer.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: x2goclient.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		x2goclientconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		x2goclient.pro \
		res/resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Svg.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5X11Extras.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile x2goclient.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
x2goclientconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
x2goclient.pro:
res/resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Svg.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5X11Extras.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile x2goclient.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res/i18n/x2goclient_de.ts res/i18n/x2goclient_da.ts res/i18n/x2goclient_es.ts res/i18n/x2goclient_et.ts res/i18n/x2goclient_fi.ts res/i18n/x2goclient_fr.ts res/i18n/x2goclient_nb_no.ts res/i18n/x2goclient_nl.ts res/i18n/x2goclient_pt.ts res/i18n/x2goclient_ru.ts res/i18n/x2goclient_sv.ts res/i18n/x2goclient_tr.ts res/i18n/x2goclient_zh_tw.ts $(DISTDIR)/
	$(COPY_FILE) --parents res/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/configdialog.h src/editconnectiondialog.h src/exportdialog.h src/imgframe.h src/LDAPSession.h src/onmainwindow.h src/sessionbutton.h src/sessionmanagedialog.h src/sshmasterconnection.h src/sshprocess.h src/SVGFrame.h src/InteractionDialog.h src/userbutton.h src/x2goclientconfig.h src/x2gologdebug.h src/printprocess.h src/cupsprint.h src/cupsprintwidget.h src/cupsprintersettingsdialog.h src/printwidget.h src/printercmddialog.h src/printdialog.h src/wapi.h src/sessionwidget.h src/configwidget.h src/connectionwidget.h src/settingswidget.h src/mediawidget.h src/sharewidget.h src/clicklineedit.h src/httpbrokerclient.h src/ongetpass.h src/onmainwindow_privat.h src/x2gosettings.h src/brokerpassdlg.h src/contest.h src/xsettingswidget.h src/appdialog.h src/x2goutils.h src/helpdialog.h src/sessionexplorer.h src/folderbutton.h src/folderexplorer.h src/non_modal_messagebox.h src/help.h src/unixhelper.h src/compat.h src/pulsemanager.h $(DISTDIR)/
	$(COPY_FILE) --parents src/sharewidget.cpp src/settingswidget.cpp src/mediawidget.cpp src/configwidget.cpp src/sessionwidget.cpp src/connectionwidget.cpp src/configdialog.cpp src/editconnectiondialog.cpp src/exportdialog.cpp src/imgframe.cpp src/LDAPSession.cpp src/onmainwindow.cpp src/sessionbutton.cpp src/sessionmanagedialog.cpp src/sshmasterconnection.cpp src/sshprocess.cpp src/SVGFrame.cpp src/InteractionDialog.cpp src/userbutton.cpp src/x2gologdebug.cpp src/printprocess.cpp src/cupsprint.cpp src/cupsprintwidget.cpp src/cupsprintersettingsdialog.cpp src/printwidget.cpp src/printercmddialog.cpp src/printdialog.cpp src/wapi.cpp src/clicklineedit.cpp src/httpbrokerclient.cpp src/ongetpass.cpp src/x2gosettings.cpp src/brokerpassdlg.cpp src/contest.cpp src/xsettingswidget.cpp src/appdialog.cpp src/x2goutils.cpp src/helpdialog.cpp src/sessionexplorer.cpp src/folderbutton.cpp src/folderexplorer.cpp src/non_modal_messagebox.cpp src/help.cpp src/unixhelper.cpp src/compat.cpp src/pulsemanager.cpp src/x2goclient.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/ui/cupsprintsettingsdialog.ui src/ui/cupsprintwidget.ui src/ui/printdialog.ui src/ui/printercmddialog.ui src/ui/printwidget.ui src/ui/xsettingsui.ui src/ui/brokerpassdialog.ui src/ui/contest.ui src/ui/appdialog.ui src/ui/helpdialog.ui src/ui/folderexplorer.ui $(DISTDIR)/
	$(COPY_FILE) --parents res/i18n/x2goclient_de.ts res/i18n/x2goclient_da.ts res/i18n/x2goclient_es.ts res/i18n/x2goclient_et.ts res/i18n/x2goclient_fi.ts res/i18n/x2goclient_fr.ts res/i18n/x2goclient_nb_no.ts res/i18n/x2goclient_nl.ts res/i18n/x2goclient_pt.ts res/i18n/x2goclient_ru.ts res/i18n/x2goclient_sv.ts res/i18n/x2goclient_tr.ts res/i18n/x2goclient_zh_tw.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_TSQM_make_all: x2goclient_de.qm x2goclient_da.qm x2goclient_es.qm x2goclient_et.qm x2goclient_fi.qm x2goclient_fr.qm x2goclient_nb_no.qm x2goclient_nl.qm x2goclient_pt.qm x2goclient_ru.qm x2goclient_sv.qm x2goclient_tr.qm x2goclient_zh_tw.qm
compiler_TSQM_clean:
	-$(DEL_FILE) x2goclient_de.qm x2goclient_da.qm x2goclient_es.qm x2goclient_et.qm x2goclient_fi.qm x2goclient_fr.qm x2goclient_nb_no.qm x2goclient_nl.qm x2goclient_pt.qm x2goclient_ru.qm x2goclient_sv.qm x2goclient_tr.qm x2goclient_zh_tw.qm
x2goclient_de.qm: res/i18n/x2goclient_de.ts
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease res/i18n/x2goclient_de.ts

x2goclient_da.qm: res/i18n/x2goclient_da.ts
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease res/i18n/x2goclient_da.ts

x2goclient_es.qm: res/i18n/x2goclient_es.ts
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease res/i18n/x2goclient_es.ts

x2goclient_et.qm: res/i18n/x2goclient_et.ts
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease res/i18n/x2goclient_et.ts

x2goclient_fi.qm: res/i18n/x2goclient_fi.ts
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease res/i18n/x2goclient_fi.ts

x2goclient_fr.qm: res/i18n/x2goclient_fr.ts
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease res/i18n/x2goclient_fr.ts

x2goclient_nb_no.qm: res/i18n/x2goclient_nb_no.ts
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease res/i18n/x2goclient_nb_no.ts

x2goclient_nl.qm: res/i18n/x2goclient_nl.ts
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease res/i18n/x2goclient_nl.ts

x2goclient_pt.qm: res/i18n/x2goclient_pt.ts
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease res/i18n/x2goclient_pt.ts

x2goclient_ru.qm: res/i18n/x2goclient_ru.ts
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease res/i18n/x2goclient_ru.ts

x2goclient_sv.qm: res/i18n/x2goclient_sv.ts
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease res/i18n/x2goclient_sv.ts

x2goclient_tr.qm: res/i18n/x2goclient_tr.ts
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease res/i18n/x2goclient_tr.ts

x2goclient_zh_tw.qm: res/i18n/x2goclient_zh_tw.ts
	/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease res/i18n/x2goclient_zh_tw.ts

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: res/resources.qrc \
		/usr/lib/x86_64-linux-gnu/qt5/bin/rcc \
		res/i18n/x2goclient_tr.qm \
		res/i18n/qt_es.qm \
		res/i18n/qt_da.qm \
		res/i18n/x2goclient_fi.qm \
		res/i18n/x2goclient_pt.qm \
		res/i18n/x2goclient_zh_tw.qm \
		res/i18n/x2goclient_ru.qm \
		res/i18n/x2goclient_de.qm \
		res/i18n/qt_pt.qm \
		res/i18n/x2goclient_sv.qm \
		res/i18n/x2goclient_fr.qm \
		res/i18n/qt_ru.qm \
		res/i18n/qt_de.qm \
		res/i18n/x2goclient_es.qm \
		res/i18n/x2goclient_da.qm \
		res/i18n/qt_zh_tw.qm \
		res/i18n/qt_fr.qm \
		res/i18n/x2goclient_nl.qm \
		res/i18n/qt_sv.qm \
		res/i18n/x2goclient_nb_no.qm \
		res/i18n/x2goclient_et.qm \
		res/img/png/ico.png \
		res/img/png/ico_mini.png \
		res/img/png/ico_440x180.png \
		res/img/png/sess_ico.png \
		res/img/png/broker-logout-button.png \
		res/img/png/power-button.png \
		res/img/icons/16x16/unity.png \
		res/img/icons/16x16/resolution.png \
		res/img/icons/16x16/cinnamon.png \
		res/img/icons/16x16/audio.png \
		res/img/icons/16x16/delete.png \
		res/img/icons/16x16/new_file.png \
		res/img/icons/16x16/xfce.png \
		res/img/icons/16x16/mate.png \
		res/img/icons/16x16/x2go.png \
		res/img/icons/16x16/trinity.png \
		res/img/icons/16x16/icewm.png \
		res/img/icons/16x16/create_file.png \
		res/img/icons/16x16/lxde.png \
		res/img/icons/16x16/rdp.png \
		res/img/icons/16x16/preferences.png \
		res/img/icons/16x16/session.png \
		res/img/icons/16x16/tbshow.png \
		res/img/icons/16x16/X.png \
		res/img/icons/16x16/edit.png \
		res/img/icons/16x16/lxqt.png \
		res/img/icons/16x16/openbox.png \
		res/img/icons/16x16/gnome.png \
		res/img/icons/16x16/kde.png \
		res/img/icons/16x16/file-open.png \
		res/img/icons/64x64/lxqt.png \
		res/img/icons/64x64/audio.png \
		res/img/icons/64x64/rdp.png \
		res/img/icons/64x64/personal.png \
		res/img/icons/64x64/lxde.png \
		res/img/icons/64x64/preferences.png \
		res/img/icons/64x64/create_file.png \
		res/img/icons/128x128/x2go.png \
		res/img/icons/128x128/lxqt.png \
		res/img/icons/128x128/rdp.png \
		res/img/icons/128x128/lxde.png \
		res/img/icons/128x128/preferences.png \
		res/img/icons/128x128/create_file.png \
		res/img/icons/128x128/folder.png \
		res/img/icons/128x128/x2gosession.png \
		res/img/icons/22x22/applications-graphics.png \
		res/img/icons/22x22/applications-games.png \
		res/img/icons/22x22/applications-internet.png \
		res/img/icons/22x22/lxqt.png \
		res/img/icons/22x22/applications-utilities.png \
		res/img/icons/22x22/applications-office.png \
		res/img/icons/22x22/applications-system.png \
		res/img/icons/22x22/applications-education.png \
		res/img/icons/22x22/applications-multimedia.png \
		res/img/icons/22x22/applications-development.png \
		res/img/icons/22x22/applications-other.png \
		res/img/icons/22x22/preferences-system.png \
		res/img/icons/32x32/detach.png \
		res/img/icons/32x32/apps.png \
		res/img/icons/32x32/suspend.png \
		res/img/icons/32x32/stop_session.png \
		res/img/icons/32x32/resolution.png \
		res/img/icons/32x32/edit_settings.png \
		res/img/icons/32x32/attach.png \
		res/img/icons/32x32/new_file.png \
		res/img/icons/32x32/reconnect.png \
		res/img/icons/32x32/tbhide.png \
		res/img/icons/32x32/exit.png \
		res/img/icons/32x32/lxde.png \
		res/img/icons/32x32/create_file.png \
		res/img/icons/32x32/rdp.png \
		res/img/icons/32x32/x2goclient.png \
		res/img/icons/32x32/preferences.png \
		res/img/icons/32x32/open_dir.png \
		res/img/icons/32x32/auth.png \
		res/img/icons/32x32/tbshow.png \
		res/img/icons/32x32/edit.png \
		res/img/icons/32x32/lxqt.png \
		res/img/icons/32x32/file-open.png \
		res/img/icons/32x32/suspend_session.png \
		res/img/icons/32x32/stop.png \
		res/img/icons/32x32/contest.png \
		res/img/svg/bg.svg \
		res/img/svg/onlogo.svg \
		res/img/svg/sessionbut_grey.svg \
		res/img/svg/x2gologo.svg \
		res/img/svg/sessionbut.svg \
		res/img/svg/folder.svg \
		res/img/svg/folder_grey.svg \
		res/img/svg/lxqt.svg \
		res/img/svg/hamburger.svg \
		res/img/svg/line.svg \
		res/img/svg/bg_hildon.svg \
		res/img/svg/passform.svg \
		res/txt/encodings \
		res/txt/packs
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name resources res/resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -m64 -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_configdialog.cpp moc_editconnectiondialog.cpp moc_exportdialog.cpp moc_imgframe.cpp moc_onmainwindow.cpp moc_sessionbutton.cpp moc_sessionmanagedialog.cpp moc_sshmasterconnection.cpp moc_sshprocess.cpp moc_SVGFrame.cpp moc_InteractionDialog.cpp moc_userbutton.cpp moc_printprocess.cpp moc_cupsprintwidget.cpp moc_cupsprintersettingsdialog.cpp moc_printwidget.cpp moc_printercmddialog.cpp moc_printdialog.cpp moc_sessionwidget.cpp moc_connectionwidget.cpp moc_settingswidget.cpp moc_mediawidget.cpp moc_sharewidget.cpp moc_clicklineedit.cpp moc_httpbrokerclient.cpp moc_brokerpassdlg.cpp moc_contest.cpp moc_xsettingswidget.cpp moc_appdialog.cpp moc_sessionexplorer.cpp moc_folderbutton.cpp moc_folderexplorer.cpp moc_pulsemanager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_configdialog.cpp moc_editconnectiondialog.cpp moc_exportdialog.cpp moc_imgframe.cpp moc_onmainwindow.cpp moc_sessionbutton.cpp moc_sessionmanagedialog.cpp moc_sshmasterconnection.cpp moc_sshprocess.cpp moc_SVGFrame.cpp moc_InteractionDialog.cpp moc_userbutton.cpp moc_printprocess.cpp moc_cupsprintwidget.cpp moc_cupsprintersettingsdialog.cpp moc_printwidget.cpp moc_printercmddialog.cpp moc_printdialog.cpp moc_sessionwidget.cpp moc_connectionwidget.cpp moc_settingswidget.cpp moc_mediawidget.cpp moc_sharewidget.cpp moc_clicklineedit.cpp moc_httpbrokerclient.cpp moc_brokerpassdlg.cpp moc_contest.cpp moc_xsettingswidget.cpp moc_appdialog.cpp moc_sessionexplorer.cpp moc_folderbutton.cpp moc_folderexplorer.cpp moc_pulsemanager.cpp
moc_configdialog.cpp: src/x2goclientconfig.h \
		src/configdialog.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/configdialog.h -o moc_configdialog.cpp

moc_editconnectiondialog.cpp: src/x2goclientconfig.h \
		src/editconnectiondialog.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/editconnectiondialog.h -o moc_editconnectiondialog.cpp

moc_exportdialog.cpp: src/x2goclientconfig.h \
		src/exportdialog.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/exportdialog.h -o moc_exportdialog.cpp

moc_imgframe.cpp: src/x2goclientconfig.h \
		src/imgframe.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/imgframe.h -o moc_imgframe.cpp

moc_onmainwindow.cpp: src/x2goclientconfig.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/onmainwindow.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/onmainwindow.h -o moc_onmainwindow.cpp

moc_sessionbutton.cpp: src/SVGFrame.h \
		src/x2goclientconfig.h \
		src/sessionbutton.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/sessionbutton.h -o moc_sessionbutton.cpp

moc_sessionmanagedialog.cpp: src/x2goclientconfig.h \
		src/sessionmanagedialog.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/sessionmanagedialog.h -o moc_sessionmanagedialog.cpp

moc_sshmasterconnection.cpp: src/sshmasterconnection.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/sshmasterconnection.h -o moc_sshmasterconnection.cpp

moc_sshprocess.cpp: src/sshmasterconnection.h \
		src/sshprocess.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/sshprocess.h -o moc_sshprocess.cpp

moc_SVGFrame.cpp: src/x2goclientconfig.h \
		src/SVGFrame.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/SVGFrame.h -o moc_SVGFrame.cpp

moc_InteractionDialog.cpp: src/x2goclientconfig.h \
		src/SVGFrame.h \
		src/InteractionDialog.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/InteractionDialog.h -o moc_InteractionDialog.cpp

moc_userbutton.cpp: src/x2goclientconfig.h \
		src/userbutton.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/userbutton.h -o moc_userbutton.cpp

moc_printprocess.cpp: src/printprocess.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/printprocess.h -o moc_printprocess.cpp

moc_cupsprintwidget.cpp: src/x2goclientconfig.h \
		src/cupsprint.h \
		ui_cupsprintwidget.h \
		src/cupsprintwidget.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/cupsprintwidget.h -o moc_cupsprintwidget.cpp

moc_cupsprintersettingsdialog.cpp: src/x2goclientconfig.h \
		ui_cupsprintsettingsdialog.h \
		src/cupsprintersettingsdialog.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/cupsprintersettingsdialog.h -o moc_cupsprintersettingsdialog.cpp

moc_printwidget.cpp: src/x2goclientconfig.h \
		ui_printwidget.h \
		src/printwidget.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/printwidget.h -o moc_printwidget.cpp

moc_printercmddialog.cpp: ui_printercmddialog.h \
		src/printercmddialog.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/printercmddialog.h -o moc_printercmddialog.cpp

moc_printdialog.cpp: ui_printdialog.h \
		src/printdialog.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/printdialog.h -o moc_printdialog.cpp

moc_sessionwidget.cpp: src/configwidget.h \
		src/x2goclientconfig.h \
		src/sessionwidget.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/sessionwidget.h -o moc_sessionwidget.cpp

moc_connectionwidget.cpp: src/configwidget.h \
		src/x2goclientconfig.h \
		src/connectionwidget.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/connectionwidget.h -o moc_connectionwidget.cpp

moc_settingswidget.cpp: src/configwidget.h \
		src/x2goclientconfig.h \
		src/settingswidget.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/settingswidget.h -o moc_settingswidget.cpp

moc_mediawidget.cpp: src/configwidget.h \
		src/x2goclientconfig.h \
		src/mediawidget.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/mediawidget.h -o moc_mediawidget.cpp

moc_sharewidget.cpp: src/configwidget.h \
		src/x2goclientconfig.h \
		src/sharewidget.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/sharewidget.h -o moc_sharewidget.cpp

moc_clicklineedit.cpp: src/clicklineedit.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/clicklineedit.h -o moc_clicklineedit.cpp

moc_httpbrokerclient.cpp: src/x2goclientconfig.h \
		src/sshmasterconnection.h \
		src/httpbrokerclient.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/httpbrokerclient.h -o moc_httpbrokerclient.cpp

moc_brokerpassdlg.cpp: ui_brokerpassdialog.h \
		src/brokerpassdlg.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/brokerpassdlg.h -o moc_brokerpassdlg.cpp

moc_contest.cpp: ui_contest.h \
		src/contest.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/contest.h -o moc_contest.cpp

moc_xsettingswidget.cpp: ui_xsettingsui.h \
		src/xsettingswidget.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/xsettingswidget.h -o moc_xsettingswidget.cpp

moc_appdialog.cpp: ui_appdialog.h \
		src/appdialog.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/appdialog.h -o moc_appdialog.cpp

moc_sessionexplorer.cpp: src/sessionexplorer.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/sessionexplorer.h -o moc_sessionexplorer.cpp

moc_folderbutton.cpp: src/SVGFrame.h \
		src/x2goclientconfig.h \
		src/folderbutton.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/folderbutton.h -o moc_folderbutton.cpp

moc_folderexplorer.cpp: ui_folderexplorer.h \
		src/folderexplorer.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/folderexplorer.h -o moc_folderexplorer.cpp

moc_pulsemanager.cpp: src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/x2goclientconfig.h \
		src/pulsemanager.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/kuscsik/code/x2go/x2goclient -I/home/kuscsik/code/x2go/x2goclient/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/pulsemanager.h -o moc_pulsemanager.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_cupsprintsettingsdialog.h ui_cupsprintwidget.h ui_printdialog.h ui_printercmddialog.h ui_printwidget.h ui_xsettingsui.h ui_brokerpassdialog.h ui_contest.h ui_appdialog.h ui_helpdialog.h ui_folderexplorer.h
compiler_uic_clean:
	-$(DEL_FILE) ui_cupsprintsettingsdialog.h ui_cupsprintwidget.h ui_printdialog.h ui_printercmddialog.h ui_printwidget.h ui_xsettingsui.h ui_brokerpassdialog.h ui_contest.h ui_appdialog.h ui_helpdialog.h ui_folderexplorer.h
ui_cupsprintsettingsdialog.h: src/ui/cupsprintsettingsdialog.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic src/ui/cupsprintsettingsdialog.ui -o ui_cupsprintsettingsdialog.h

ui_cupsprintwidget.h: src/ui/cupsprintwidget.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic src/ui/cupsprintwidget.ui -o ui_cupsprintwidget.h

ui_printdialog.h: src/ui/printdialog.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic src/ui/printdialog.ui -o ui_printdialog.h

ui_printercmddialog.h: src/ui/printercmddialog.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic src/ui/printercmddialog.ui -o ui_printercmddialog.h

ui_printwidget.h: src/ui/printwidget.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic src/ui/printwidget.ui -o ui_printwidget.h

ui_xsettingsui.h: src/ui/xsettingsui.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic src/ui/xsettingsui.ui -o ui_xsettingsui.h

ui_brokerpassdialog.h: src/ui/brokerpassdialog.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic src/ui/brokerpassdialog.ui -o ui_brokerpassdialog.h

ui_contest.h: src/ui/contest.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic src/ui/contest.ui -o ui_contest.h

ui_appdialog.h: src/ui/appdialog.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic src/ui/appdialog.ui -o ui_appdialog.h

ui_helpdialog.h: src/ui/helpdialog.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic src/ui/helpdialog.ui -o ui_helpdialog.h

ui_folderexplorer.h: src/ui/folderexplorer.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic src/ui/folderexplorer.ui -o ui_folderexplorer.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_TSQM_clean compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

sharewidget.o: src/sharewidget.cpp src/sharewidget.h \
		src/configwidget.h \
		src/x2goclientconfig.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/x2gologdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sharewidget.o src/sharewidget.cpp

settingswidget.o: src/settingswidget.cpp src/settingswidget.h \
		src/configwidget.h \
		src/x2goclientconfig.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/x2gologdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingswidget.o src/settingswidget.cpp

mediawidget.o: src/mediawidget.cpp src/mediawidget.h \
		src/configwidget.h \
		src/x2goclientconfig.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/x2gologdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mediawidget.o src/mediawidget.cpp

configwidget.o: src/configwidget.cpp src/configwidget.h \
		src/x2goclientconfig.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configwidget.o src/configwidget.cpp

sessionwidget.o: src/sessionwidget.cpp src/sessionwidget.h \
		src/configwidget.h \
		src/x2goclientconfig.h \
		src/x2goutils.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/folderexplorer.h \
		ui_folderexplorer.h \
		src/sessionexplorer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sessionwidget.o src/sessionwidget.cpp

connectionwidget.o: src/connectionwidget.cpp src/connectionwidget.h \
		src/configwidget.h \
		src/x2goclientconfig.h \
		src/x2gosettings.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/wapi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectionwidget.o src/connectionwidget.cpp

configdialog.o: src/configdialog.cpp src/x2gosettings.h \
		src/onmainwindow.h \
		src/x2goclientconfig.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/wapi.h \
		src/configdialog.h \
		src/x2gologdebug.h \
		src/printwidget.h \
		ui_printwidget.h \
		src/connectionwidget.h \
		src/configwidget.h \
		src/settingswidget.h \
		src/mediawidget.h \
		src/x2goutils.h \
		src/xsettingswidget.h \
		ui_xsettingsui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configdialog.o src/configdialog.cpp

editconnectiondialog.o: src/editconnectiondialog.cpp src/editconnectiondialog.h \
		src/x2goclientconfig.h \
		src/x2gologdebug.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/sessionwidget.h \
		src/configwidget.h \
		src/sharewidget.h \
		src/connectionwidget.h \
		src/settingswidget.h \
		src/mediawidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editconnectiondialog.o src/editconnectiondialog.cpp

exportdialog.o: src/exportdialog.cpp src/x2goclientconfig.h \
		src/exportdialog.h \
		src/editconnectiondialog.h \
		src/x2gosettings.h \
		src/sessionbutton.h \
		src/SVGFrame.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/wapi.h \
		src/sessionexplorer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exportdialog.o src/exportdialog.cpp

imgframe.o: src/imgframe.cpp src/imgframe.h \
		src/x2goclientconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgframe.o src/imgframe.cpp

LDAPSession.o: src/LDAPSession.cpp src/LDAPSession.h \
		src/x2goclientconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LDAPSession.o src/LDAPSession.cpp

onmainwindow.o: src/onmainwindow.cpp src/onmainwindow_privat.h \
		src/version.h \
		src/x2goclientconfig.h \
		src/x2goutils.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/userbutton.h \
		src/exportdialog.h \
		src/printprocess.h \
		src/helpdialog.h \
		ui_helpdialog.h \
		src/appdialog.h \
		ui_appdialog.h \
		src/InteractionDialog.h \
		src/SVGFrame.h \
		src/httpbrokerclient.h \
		src/imgframe.h \
		src/clicklineedit.h \
		src/brokerpassdlg.h \
		ui_brokerpassdialog.h \
		src/contest.h \
		ui_contest.h \
		src/configdialog.h \
		src/editconnectiondialog.h \
		src/sessionbutton.h \
		src/folderbutton.h \
		src/sessionexplorer.h \
		src/sessionmanagedialog.h \
		src/x2gologdebug.h \
		src/help.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o onmainwindow.o src/onmainwindow.cpp

sessionbutton.o: src/sessionbutton.cpp src/sessionbutton.h \
		src/SVGFrame.h \
		src/x2goclientconfig.h \
		src/x2goutils.h \
		src/x2gosettings.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/wapi.h \
		src/x2gologdebug.h \
		src/sessionexplorer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sessionbutton.o src/sessionbutton.cpp

sessionmanagedialog.o: src/sessionmanagedialog.cpp src/x2goclientconfig.h \
		src/sessionmanagedialog.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/x2gologdebug.h \
		src/sessionbutton.h \
		src/SVGFrame.h \
		src/folderbutton.h \
		src/sessionexplorer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sessionmanagedialog.o src/sessionmanagedialog.cpp

sshmasterconnection.o: src/sshmasterconnection.cpp src/x2goclientconfig.h \
		src/x2gologdebug.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/sshprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sshmasterconnection.o src/sshmasterconnection.cpp

sshprocess.o: src/sshprocess.cpp src/x2goclientconfig.h \
		src/x2gologdebug.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/sshprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sshprocess.o src/sshprocess.cpp

SVGFrame.o: src/SVGFrame.cpp src/SVGFrame.h \
		src/x2goclientconfig.h \
		src/x2gologdebug.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SVGFrame.o src/SVGFrame.cpp

InteractionDialog.o: src/InteractionDialog.cpp src/InteractionDialog.h \
		src/x2goclientconfig.h \
		src/SVGFrame.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InteractionDialog.o src/InteractionDialog.cpp

userbutton.o: src/userbutton.cpp src/x2goclientconfig.h \
		src/userbutton.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userbutton.o src/userbutton.cpp

x2gologdebug.o: src/x2gologdebug.cpp src/x2gologdebug.h \
		src/x2goclientconfig.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o x2gologdebug.o src/x2gologdebug.cpp

printprocess.o: src/printprocess.cpp src/x2goclientconfig.h \
		src/printprocess.h \
		src/x2gologdebug.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/printdialog.h \
		ui_printdialog.h \
		src/cupsprint.h \
		src/printwidget.h \
		ui_printwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o printprocess.o src/printprocess.cpp

cupsprint.o: src/cupsprint.cpp src/cupsprint.h \
		src/x2goclientconfig.h \
		src/x2gologdebug.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cupsprint.o src/cupsprint.cpp

cupsprintwidget.o: src/cupsprintwidget.cpp src/cupsprint.h \
		src/x2goclientconfig.h \
		src/cupsprintwidget.h \
		ui_cupsprintwidget.h \
		src/x2gologdebug.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/cupsprintersettingsdialog.h \
		ui_cupsprintsettingsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cupsprintwidget.o src/cupsprintwidget.cpp

cupsprintersettingsdialog.o: src/cupsprintersettingsdialog.cpp src/cupsprintersettingsdialog.h \
		src/x2goclientconfig.h \
		ui_cupsprintsettingsdialog.h \
		src/cupsprint.h \
		src/x2goutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cupsprintersettingsdialog.o src/cupsprintersettingsdialog.cpp

printwidget.o: src/printwidget.cpp src/printwidget.h \
		src/x2goclientconfig.h \
		ui_printwidget.h \
		src/cupsprintwidget.h \
		src/cupsprint.h \
		ui_cupsprintwidget.h \
		src/printercmddialog.h \
		ui_printercmddialog.h \
		src/x2gosettings.h \
		src/x2gologdebug.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/wapi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o printwidget.o src/printwidget.cpp

printercmddialog.o: src/printercmddialog.cpp src/printercmddialog.h \
		ui_printercmddialog.h \
		src/x2goclientconfig.h \
		src/printwidget.h \
		ui_printwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o printercmddialog.o src/printercmddialog.cpp

printdialog.o: src/printdialog.cpp src/printdialog.h \
		ui_printdialog.h \
		src/printwidget.h \
		src/x2goclientconfig.h \
		ui_printwidget.h \
		src/x2gologdebug.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o printdialog.o src/printdialog.cpp

wapi.o: src/wapi.cpp src/x2goclientconfig.h \
		src/wapi.h \
		src/x2gologdebug.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wapi.o src/wapi.cpp

clicklineedit.o: src/clicklineedit.cpp src/clicklineedit.h \
		src/x2gologdebug.h \
		src/x2goclientconfig.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clicklineedit.o src/clicklineedit.cpp

httpbrokerclient.o: src/httpbrokerclient.cpp src/httpbrokerclient.h \
		src/x2goclientconfig.h \
		src/sshmasterconnection.h \
		src/x2gologdebug.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/SVGFrame.h \
		src/InteractionDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpbrokerclient.o src/httpbrokerclient.cpp

ongetpass.o: src/ongetpass.cpp src/ongetpass.h \
		src/x2goclientconfig.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/x2gologdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ongetpass.o src/ongetpass.cpp

x2gosettings.o: src/x2gosettings.cpp src/x2gosettings.h \
		src/x2goclientconfig.h \
		src/x2gologdebug.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/wapi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o x2gosettings.o src/x2gosettings.cpp

brokerpassdlg.o: src/brokerpassdlg.cpp src/brokerpassdlg.h \
		ui_brokerpassdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brokerpassdlg.o src/brokerpassdlg.cpp

contest.o: src/contest.cpp src/contest.h \
		ui_contest.h \
		src/x2gologdebug.h \
		src/x2goclientconfig.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/httpbrokerclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contest.o src/contest.cpp

xsettingswidget.o: src/xsettingswidget.cpp src/xsettingswidget.h \
		ui_xsettingsui.h \
		src/x2gosettings.h \
		src/x2goutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xsettingswidget.o src/xsettingswidget.cpp

appdialog.o: src/appdialog.cpp src/appdialog.h \
		ui_appdialog.h \
		src/onmainwindow.h \
		src/x2goclientconfig.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o appdialog.o src/appdialog.cpp

x2goutils.o: src/x2goutils.cpp src/x2goutils.h \
		src/onmainwindow.h \
		src/x2goclientconfig.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/x2gologdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o x2goutils.o src/x2goutils.cpp

helpdialog.o: src/helpdialog.cpp src/helpdialog.h \
		ui_helpdialog.h \
		src/x2goutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpdialog.o src/helpdialog.cpp

sessionexplorer.o: src/sessionexplorer.cpp src/sessionexplorer.h \
		src/sessionbutton.h \
		src/SVGFrame.h \
		src/x2goclientconfig.h \
		src/folderbutton.h \
		src/editconnectiondialog.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/x2goutils.h \
		src/imgframe.h \
		src/x2gologdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sessionexplorer.o src/sessionexplorer.cpp

folderbutton.o: src/folderbutton.cpp src/folderbutton.h \
		src/SVGFrame.h \
		src/x2goclientconfig.h \
		src/x2goutils.h \
		src/x2gosettings.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/wapi.h \
		src/x2gologdebug.h \
		src/sessionexplorer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o folderbutton.o src/folderbutton.cpp

folderexplorer.o: src/folderexplorer.cpp src/folderexplorer.h \
		ui_folderexplorer.h \
		src/x2gologdebug.h \
		src/x2goclientconfig.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/sessionexplorer.h \
		src/folderbutton.h \
		src/SVGFrame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o folderexplorer.o src/folderexplorer.cpp

non_modal_messagebox.o: src/non_modal_messagebox.cpp src/non_modal_messagebox.h \
		src/x2goutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o non_modal_messagebox.o src/non_modal_messagebox.cpp

help.o: src/help.cpp src/help.h \
		src/version.h \
		src/x2gologdebug.h \
		src/x2goclientconfig.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/x2goutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o help.o src/help.cpp

unixhelper.o: src/unixhelper.cpp src/unixhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unixhelper.o src/unixhelper.cpp

compat.o: src/compat.cpp src/compat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compat.o src/compat.cpp

pulsemanager.o: src/pulsemanager.cpp src/pulsemanager.h \
		src/windows_stdint.h \
		src/unix_stdint.h \
		src/x2gosettings.h \
		src/wapi.h \
		src/x2goclientconfig.h \
		src/x2gologdebug.h \
		src/onmainwindow.h \
		src/LDAPSession.h \
		src/sshmasterconnection.h \
		src/non_modal_messagebox.h \
		src/x2goutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pulsemanager.o src/pulsemanager.cpp

x2goclient.o: src/x2goclient.cpp src/unixhelper.h \
		src/ongetpass.h \
		src/compat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o x2goclient.o src/x2goclient.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_configdialog.o: moc_configdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configdialog.o moc_configdialog.cpp

moc_editconnectiondialog.o: moc_editconnectiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editconnectiondialog.o moc_editconnectiondialog.cpp

moc_exportdialog.o: moc_exportdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exportdialog.o moc_exportdialog.cpp

moc_imgframe.o: moc_imgframe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imgframe.o moc_imgframe.cpp

moc_onmainwindow.o: moc_onmainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_onmainwindow.o moc_onmainwindow.cpp

moc_sessionbutton.o: moc_sessionbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sessionbutton.o moc_sessionbutton.cpp

moc_sessionmanagedialog.o: moc_sessionmanagedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sessionmanagedialog.o moc_sessionmanagedialog.cpp

moc_sshmasterconnection.o: moc_sshmasterconnection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sshmasterconnection.o moc_sshmasterconnection.cpp

moc_sshprocess.o: moc_sshprocess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sshprocess.o moc_sshprocess.cpp

moc_SVGFrame.o: moc_SVGFrame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SVGFrame.o moc_SVGFrame.cpp

moc_InteractionDialog.o: moc_InteractionDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_InteractionDialog.o moc_InteractionDialog.cpp

moc_userbutton.o: moc_userbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userbutton.o moc_userbutton.cpp

moc_printprocess.o: moc_printprocess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_printprocess.o moc_printprocess.cpp

moc_cupsprintwidget.o: moc_cupsprintwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cupsprintwidget.o moc_cupsprintwidget.cpp

moc_cupsprintersettingsdialog.o: moc_cupsprintersettingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cupsprintersettingsdialog.o moc_cupsprintersettingsdialog.cpp

moc_printwidget.o: moc_printwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_printwidget.o moc_printwidget.cpp

moc_printercmddialog.o: moc_printercmddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_printercmddialog.o moc_printercmddialog.cpp

moc_printdialog.o: moc_printdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_printdialog.o moc_printdialog.cpp

moc_sessionwidget.o: moc_sessionwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sessionwidget.o moc_sessionwidget.cpp

moc_connectionwidget.o: moc_connectionwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connectionwidget.o moc_connectionwidget.cpp

moc_settingswidget.o: moc_settingswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingswidget.o moc_settingswidget.cpp

moc_mediawidget.o: moc_mediawidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mediawidget.o moc_mediawidget.cpp

moc_sharewidget.o: moc_sharewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sharewidget.o moc_sharewidget.cpp

moc_clicklineedit.o: moc_clicklineedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clicklineedit.o moc_clicklineedit.cpp

moc_httpbrokerclient.o: moc_httpbrokerclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httpbrokerclient.o moc_httpbrokerclient.cpp

moc_brokerpassdlg.o: moc_brokerpassdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_brokerpassdlg.o moc_brokerpassdlg.cpp

moc_contest.o: moc_contest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contest.o moc_contest.cpp

moc_xsettingswidget.o: moc_xsettingswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_xsettingswidget.o moc_xsettingswidget.cpp

moc_appdialog.o: moc_appdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_appdialog.o moc_appdialog.cpp

moc_sessionexplorer.o: moc_sessionexplorer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sessionexplorer.o moc_sessionexplorer.cpp

moc_folderbutton.o: moc_folderbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_folderbutton.o moc_folderbutton.cpp

moc_folderexplorer.o: moc_folderexplorer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_folderexplorer.o moc_folderexplorer.cpp

moc_pulsemanager.o: moc_pulsemanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pulsemanager.o moc_pulsemanager.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

