Document: x2goclient
Title: Debian x2goclient Manual
Author: <insert document author here>
Abstract: This manual describes what x2goclient is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/x2goclient/x2goclient.sgml.gz

Format: postscript
Files: /usr/share/doc/x2goclient/x2goclient.ps.gz

Format: text
Files: /usr/share/doc/x2goclient/x2goclient.text.gz

Format: HTML
Index: /usr/share/doc/x2goclient/html/index.html
Files: /usr/share/doc/x2goclient/html/*.html

  
